### ISSUE TITLE
Windows Build?

### ISSUE THREAD

**Issue by Riajyuu** [persepolisdm/persepolis#139]
Could you add a Windows build? I'm pretty sure it can be done with same kit.

**Comment by alireza-amirsamimi** [comment]
We bulit exe package successfully , but we did'nt publish it . We want to add some new features to Persepolis Download Manager. When we release version 2.4 (our next release)  , we also publish exe package :) .

**Comment by hayyan71** [comment]
There is a windows version, but not publicly available, because it's beta. Currently they are working on the windows version. you have to wait until version 2.4...

**Comment by smaragdus** [comment]
You announced that with version 2.4 you release an official Windows version of Persepolis Download Manager but I could not find it. Where is it?

**Comment by alireza-amirsamimi** [comment]
@smaragdus We upload it very very soon :)

**Comment by smaragdus** [comment]
**@alireza-amirsamimi**
Thanks! I am impatient to see Persepolis Download Manager in action on Windows. ;)
You may also update the Wiki and Persepolis web-site adding Windows installation instructions.

**Comment by alireza-amirsamimi** [comment]
@smaragdus Thank you very much :) we update them very soon

**Comment by smaragdus** [comment]
**@alireza-amirsamimi**

Hello, unfortunately Persepolis Download Manager version 2.4 x64 fails to run on my Windows 8 x64 system- when I start it I get the following error:

"Failed to execute script Persepolis Download Manager"

Screen-shot:
![persepolis download manager 2 4 - 2017-04-15 - error - 001](https://cloud.githubusercontent.com/assets/9025757/25062504/e36ca71e-21d5-11e7-81ce-e0d83f6fdc87.png)

Are there any special requirements?

**Comment by alireza-amirsamimi** [comment]
@smaragdus 
Hello 

we tested it on Windows7 and Windows10 and it was ok!
I will report this problem to @mostafaasadi  (who made the exe package) for checking the problem.
thanks for reporting.

**Comment by alireza-amirsamimi** [comment]
@smaragdus 
Hello
We released a [newer version](https://github.com/persepolisdm/persepolis/releases/tag/2.4.1)
Please check again.
Thanks

**Comment by smaragdus** [comment]
**@alireza-amirsamimi**

Thank you very much for the notification about the new version and for the immediate fix of the problem I encountered with **Persepolis Download Manager** version **2.4.0** on Windows 8 x64. The new version- **2.4.1**, installs and runs fine, good work, thanks. _Firefox_ integration via _FlashGot_ also works fine.

However I have several suggestions:
 - An option option to get the original date and time from download server, as far as I know _aria2_ supports this. This option is labelled "Set the date of a file identical to the date specified by the server" in _Free Download Manager_ options.
 - An option to monitor clipboard for download links.
 - A drop box (drop basket) with customizable position on desktop- the user drags and drops download links to this small drop box on desktop and the downloads are added.
 - On program start 3 console windows show up, can these windows be hidden? It is not of great importance, it would be just more aesthetically pleasing.
 - New context menu command - right click on a download- **Restart Download**.
 - In context menu you may change **delete file** command to **Delete file** to match the overall style, screen-shot below.
![persepolis download manager 2 4 1 - 2017-04-16 - 015](https://cloud.githubusercontent.com/assets/9025757/25066979/45dcced4-223e-11e7-802b-db5c8ac8ce1b.png)
 - In context menu some if the commands (**Resume Download**, **Pause Download**, **Stop Download**, **Progress**) use different font style- I presume this done on purpose but I think that unified style would look better.
 - Since I like green colour I would also enjoy a new "Green" colour scheme (of course this is not of great importance).
 - Portable version-, on Windows **Persepolis Download Manager** saves data and settings in AppData (C:\Users\UserName\AppData\Local\persepolis_download_manager). I would appreciate a truly portable version which saves data and settings in its program folder- it would be handy to be able to carry **Persepolis Download Manager** on external drives with all its data and settings and run in on other machines without installation and without leaving any traces behind. This may be implemented in different ways- "portable mode installation", dedicated portable version- archive with binaries- settings saved to program folder, command line switch- for example "Persepolis Download Manager.exe --portable", etc.

I appreciate your work on **Persepolis Download Manager** very much. My default download manager is still _Free Download Manager_ but I use an old version (3.9.7) because the new one is terrible- both visually and functionally. So I think I will follow the development of your download manager.

**Comment by morealaz** [comment]
@smaragdus سلام
آقا پیرو پیشنهادات این دوستمون
من پیشنهاد می کنم برای ویندوز این دو تا گزینه رو هم در نظر بگیرید:
https://chocolatey.org/

**Comment by alireza-amirsamimi** [comment]
@smaragdus 
Thanks for your feature requests 👍 We work on them.
About theme:
 We will work on green theme but  you can also change persepolis theme . [ please read this](https://github.com/persepolisdm/persepolis/wiki/How-to-change-Persepolis-theme)

@EMLVIRUS  @smaragdus 
Thanks for opening this issue and asking for windows version . It was a motivation for us :)

We released windows version so I close this issue . feel free to open new issue for asking question or bug report or feature request.
