### ISSUE TITLE
some suggestion

### ISSUE THREAD

**Issue by aminbahraini** [persepolisdm/persepolis#188]
first of all thanks for THE amazing presepolis 👌🙂

i have some suggestion for you:

1. column customization isn't complete ("last try date" and "category" not on the list?!!) 
2. there isn't sort??!! (i want to sort my dl list by size or status or ...) 
3. add a button for clear complete dl from the list.
4. add a schedule (like idm)

Thanks.👍

**Comment by alireza-amirsamimi** [comment]
Hello
thanks🌹
1. resize your preferences window (make it bigger), then you can see it :)

![window](https://cloud.githubusercontent.com/assets/7452500/25249626/b9b97220-2627-11e7-9c1a-ac1241af183e.png)

2. Just right click on your download section then you can find it :)

![sort](https://cloud.githubusercontent.com/assets/7452500/25249770/5d275daa-2628-11e7-9d70-817b3f358dd2.png)

3. Click on your download item for selecting item , then click on trash button or cross button . trash button delete downloaded file too. for selecting multiple items , right click on download list and select "select multiple items" . If you are linux user you can clear every thing (some thing like factory reset) by this command:
```
persepolis --clear
```

4. I don't now how IDM schedule downloads , because I'm ArchLinux user , I'm not Windows user and IDM user. but persepolis have schedule and download queue. Please read persepolis [WIKI](https://github.com/persepolisdm/persepolis/wiki) for more information:
[FAQ-english](https://github.com/persepolisdm/persepolis/wiki/Home-en#faq)
[FAQ-farsi](https://github.com/persepolisdm/persepolis/wiki/Home-en#faq)

Good luck

**Comment by aminbahraini** [comment]
1-😅 thanks (but where is the scroll bar!)
2-thanks again (thats my bad , i search eveywhere except on the right click 😅)
3-
![idm1](https://cloud.githubusercontent.com/assets/20213473/25253090/b56170da-2634-11e7-81ee-a6410a81243e.png)
i know that but i mean i think its be great if there was a button.

im linux user(any way) but im new at it.🤓

4-
![s-5](https://cloud.githubusercontent.com/assets/20213473/25253137/dfb6dd34-2634-11e7-90ca-f239436d3d5f.png)
schedule is one of the best thing that idm has.
you can make a plan for it 👏 👏 👏

**Comment by alireza-amirsamimi** [comment]
4- you can schedule your downloads with persepolis. Please read persepolis wiki.
You can also create queue
https://github.com/persepolisdm/persepolis/wiki/Home-en#faq

**Comment by wax911** [comment]
I'd also like to thank the team for the amazing work on Persepolis, coming from windows some months back and finding such a nice GUI download manager has made the migration less of a hustle, Would it be possible to have a feature which only opens the download confirmation dialog without opening the main program window? 

Perhaps keeping the main window minimized in the system tray and only having the dialog confirmation showing. Then after confirming a download, can a user set preferences on whether or not they want to see a downloading progress dialog or not. I apologize for the long read and thank you once more!

**Comment by alireza-amirsamimi** [comment]
@wax911 
ُThanks for your feature requests :) we will work on them.
feel free to open new issue for every new request or question or bug , ... .

**Comment by alireza-amirsamimi** [comment]
I add this feature :)
So users can minimize Persepolis to the system tray with close(x) button.
Thanks for your feature request :+1:
