### ISSUE TITLE
Custom aria2 location

### ISSUE THREAD

**Issue by dimqua** [persepolisdm/persepolis#315]
Please provide a possibility to specify location of the aria2c executable file.

**Comment by alireza-amirsamimi** [comment]
Hello
why is it useful?
and what is your operating system?
Thank you :)

**Comment by dimqua** [comment]
On MS Windows platform you can update aria2 [manually](https://github.com/aria2/aria2/releases) or [by using](https://chocolatey.org/packages/aria2) chocolatey package manager. In both cases you may want to set custom aria2 executable location in Persepolis to always use the latest aria2 version. 

BTW, Persipolis [will be available](https://chocolatey.org/packages/persepolis) at the chocolatey repository soon.

I'm not sure whatever it's useful for GNU/Linux version, though. Probably, not.

**Comment by alireza-amirsamimi** [comment]
Thanks for your explanations :)
Ok, I will add it soon for next version.

**Comment by alireza-amirsamimi** [comment]
I add your feature request.
In next version of persepolis user can select custom aria2 path in Windows and Mac :)

**Comment by DRSDavidSoft** [comment]
@alireza-amirsamimi Sorry to bother you here,

Can I use Persepolis with an already running `aria2c`/RPC? How does persepolis connect to an _existing_ aria2c instance, instead of running the built-in version internally?

I'd like to share a working aria2c installation that I use with web UI, such as:
- https://ziahamza.github.io/webui-aria2/
- http://aria2.net/
