### ISSUE TITLE
when download from chrome its not work

### ISSUE THREAD

**Issue by amirhemmateenejad** [persepolisdm/persepolis#352]
**System Details:**
* Operating System: linux
* Distro(For GNU/Linux and BSD users): xubunu
* Desktop Environment(For GNU/Linux and BSD users): xfce
* Persepolis Version: 3
* How do you install Persepolis? (Repositories, source, ...) repositories

* _Please attach log files if crash or paste error message_

when i'm in chrome and persepolis extension is on and i click one link persepolis not work but when i go to persepolis application and click ad new download link and paste link it's work and download please fix extension

**Comment by alireza-amirsamimi** [comment]
@Amir-hn Hello
Can you explain more, please?
What do you mean, when you said "not work"?
Persepolis wouldn't open? or ...

**Comment by amirhemmateenejad** [comment]
@alireza-amirsamimi hello
yes Persepolis not open and Nothing happens but when turn off extension and click on link it's downloaded by chrome or when copy link and click add new downloaded link in persspolise its downloaded successfully

**Comment by alireza-amirsamimi** [comment]
@Amir-hn First of all, make sure you have the latest version of extension on your browser (you can uninstall extension and then install it again).

If problem didn't solve, then keep persepolis open and click on your link. Is link added to persepolis?

Please tell me the result.

**Comment by amirhemmateenejad** [comment]
@alireza-amirsamimi I uninstall extension and downloaded again and open main of persepolis download manager and right click a image then click download with persepolis download manager but its didn't work

**Comment by Amir-hn** [comment]
@alireza-amirsamimi i uninstall and reinstall per

**Comment by amirhemmateenejad** [comment]
@alireza-amirsamimi i reinstall1 persepolis 3 this time persepolis has closed unexpectedly and title of this is:

persepolis crashed with sqlite3.OperationalError in insertlnPluginTable(): no such table: plugin_db_table

and traceback say file "./persepolis" line 40, in <module> from persepolis import __main__ file /usr/share/persepolis/__main__.py", line 5, in <module> from persepolis.scripts import persepolis file "/usr/share/persepolis/scripts/persepolis.py", line 350, in <module> plugins_db.insertlnPluginsTable(plugin_list) file "/usr/share/persepolis/scripts/data_base.py", line 311, in insertlnPLuginsTable)""",dict) sqlite3.OperationalError: no such table: plugins_db_table

Thanks in advance for your follow up

**Comment by alireza-amirsamimi** [comment]
Perhaps you have some problem in your `/tmp` folder. persepolis coudn't create data base in your `/tmp`.

Please run this command.
`df -H /tmp`

do you have free space on `/tmp` ?

what is the result of this command?
`cat ~/.config/persepolis_download_manager/persepolisdm.log`

**Comment by alireza-amirsamimi** [comment]
We released new version(3.0.1) and I hope that you haven't this problem any more, Because I changed temp folder path :)
Please update persepolis.
Thanks for reporting this problem!

**Comment by Dellandu** [comment]
System Details:

Operating System: Windows 10 64-bit Build 17763.475

Distro(For GNU/Linux and BSD users): 

Desktop Environment(For GNU/Linux and BSD users): 

Persepolis Version: 3.1.0

Chrome Extension Version: 2.0

How do you install Persepolis? (Repositories, source, ...) repositories

Please attach log files if crash or paste error message
There is no Log generated. I have Comodo Firewall installed, but aria2c and Persepolis are both flagged as trusted.

Same symptoms here, it won't catch download requests (either by clicking the link or by context menu), even with interrupt downloads toggled. Creating new download by pasting links in the client works fine. I've un and reinstalled both the client and extension to no avail.

It might be caused by my system environment, for FDM's (Free Download Manager) chrome extension failed to catch download requests recently (it worked before). The difference is FDM detects context menu requests correctly...

**Comment by JafarAkhondali** [comment]
Hey @Dellandu ,
It's probably a problem with your system, since no other members mentioned this yet.
Open `regedit.exe` and go to this path:
`HKEY_CURRENT_USER\Software\Google\Chrome\NativeMessagingHosts\com.persepolis.pdmchromewrapper`

It should contain something like:
`C:\Users\YOUR_USER_NAME\AppData\Local\persepolis_download_manager\chrome\com.persepolis.pdmchromewrapper.json`

If the value is missing, you should create it. Here is mine:
![image](https://user-images.githubusercontent.com/11364402/57580182-9b9d6280-74bb-11e9-96a6-7835fc3dbfbc.png)


If the json file is missing, you should create it( with same name and path as above) with this value:

```
{"description": "Integrate Persepolis with vivaldi using WebExtensions", "path": "C:\\\\Program Files\\\\Persepolis Download Manager\\\\Persepolis Download Manager.exe", "allowed_origins": ["chrome-extension://legimlagjjoghkoedakdjhocbeomojao/"], "name": "com.persepolis.pdmchromewrapper", "type": "stdio"}
``` 

Don't forget to change path if you changed default location of Persepolis.

If none of above solved your problem, probably a re-installation of Persepolis will solve this problem.

**Comment by Dellandu** [comment]
Hi @JafarAkhondali,

Both of the reg entry and the json file are presented in my system, so it's probably the interference or conflict with some other program. I didn't install other new program, so my guess are Windows / Chrome / Comodo updates, considering how both FDM and Persepolis failed to catch downloads all the sudden...

Anyhow thanks for your help, I will stick with pasting URLs for now, maybe it will work for me again after future updates.

**Comment by amin3536** [comment]
I have the same problem in ubuntu genome chromium-browser 
please help 
how can I solve it ?

**Comment by AshkanGanj** [comment]
Hi 
I have the same problem in pop os 21.04; after clicking on the link and select download with Perspolise, nothing happened :(.

**Comment by Ali-Aref** [comment]
still the same problem here! any solutions ?

**Comment by QasimAbbasi9497** [comment]
i am also facing same problem on Arch
