### ISSUE TITLE
i could not upgrade 3.0.1 to 3.1 [issue]

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#478]
**System Details:**
* Operating System: linux
* Distro(For GNU/Linux and BSD users): ubuntu 16.04
* Desktop Environment(For GNU/Linux and BSD users): unity
* Persepolis Version: 3.0.1
* How do you install Persepolis? Repositories

I cant upgrade 3.0.1 to 3.1 from the repository 
source of the problem is two dependency 
```
adwaita-qt (>= 0.5) but it is not installable
youtube-dl (>= 2017.05.18) but 2016.02.22-1 is to be installed
```
i try update youtube-dl by below code but it's not helpfull
` pip install --upgrade youtube-dl`

**Comment by mostafaasadi** [comment]
Hi @Monirzadeh 
i approve this bug , I rebuild package for 16.04 as soon as I can

**Comment by jkmpariab** [comment]
same problem for me with the same system details

**Comment by candrapersada** [comment]
please wait for ubuntu 18.04 lts.

**Comment by alireza-amirsamimi** [comment]
The problem is related to some old package in older debian base distros(Ubuntu 16.04, ...).
As a workaround, [Use this way](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction#installing-dependencies-for-debian-and-debian-base-distros-ubuntu--) for installing persepolis.

@mostafaasadi will fix the package for older debian base distributions.

**Comment by Monirzadeh** [comment]
alireza amirsamimi it does not solve the problem
`sudo pip3 install youtube-dl`

get this error 
>  Requirement already satisfied: youtube-dl in /usr/local/lib/python3.5/dist-packages

i am not sure but I think the problem is for my pc config similar [this issue](https://github.com/pypa/pip/issues/3776) but I can't solve
`sudo apt-get install adwaita-qt`
give me this error
> Package adwaita-qt is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source

**Comment by alireza-amirsamimi** [comment]
So you have not problem with youtube-dl! 
Your problem is adwaita-qt! It's optional dependency. You can ignore it! Try installing persepolis from [source](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction#linux).

**Comment by jkmpariab** [comment]
installing from source worked perfectly. thank you!

**Comment by Monirzadeh** [comment]
installing from source solved the problem. thanks.
minor bug
after installing from source Persepolis.desktop file from the last version does not remove from /usr/share/applications so two Persepolis application icon present into application list
i  removed manually one of them

**Comment by alireza-amirsamimi** [comment]
@Monirzadeh 
ُThank you. Run this code for solving this issue:

```sudo rm /usr/share/applications/persepolis.desktop```

**Comment by alireza-amirsamimi** [comment]
unfortunately, We  must drop ubuntu 16.04 support.
Because youtube-dl package in official repository for ubuntu 16.04 is very old! and persepolis needs newer youtube-dl.
Ubuntu 16.04 users can install persepolis from [source](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction#linux)
