### ISSUE TITLE
Report a few problems on Mac OS

### ISSUE THREAD

**Issue by abbasnaqdi** [persepolisdm/persepolis#487]
Persepolis Version: 3.1.0
Operating system version: 10.13.4

Hello . I use Mac OS and I have problems.

1: After clicking the close button, Perspolis is closed, if this is not normal for Mac applications and should not be closed (usually the applications are closed on the Mac with Quit)

2: Persepolis is too busy and uses more CPU than other downloaders.

3: The graphics of this super-ugly downloader have dropped me out of Windows 98: Please add graphics to this download manager. UI is the ugliest download to me :) and ux is also a copy of IDM. .

4: After clicking on the minimize button, minimize Perspex, but when I click Perspolis I will not return to maximize, and I have to close Persepolis and reopen it.

These problems are the result of 10 minutes of working with Persepolis and the first time I installed it, these problems will have to stay alive.

Please fix these problems.

**Comment by alireza-amirsamimi** [comment]
Hello
1. We use CTRL+W in Gnu/Linux for minimizing.Perhaps It's Super key+W in mac.
2. It's not normal! It must be checked.
3. Every thing looks good in Gnu/Linux. [Please read help for changing theme in your os](https://github.com/persepolisdm/persepolis/wiki/How-to-change-Persepolis-theme).
This is persepolis on Archlinux and KDE.
![screenshot_20180331_200728](https://user-images.githubusercontent.com/7452500/38172426-8fd348a0-35c1-11e8-8ec7-de8ecebbdc31.png)

I'm not windows user or Mac user or IDM user.

4. This problem is related to Mac. I haven't this problem in Gnu/Linux. We'll check the problem.

Thanks for reporting.  Most of your problems are related to your OS. many of persepolis developers are Gnu/Linux users. @Mr0Null is our Mac tester and one of developers. He will check the problems that you reported. 

1- The english report is enough for us. No need to farsi subtitle.
2- Please keep calm first(May a glass of water and deep breath help you) and then open the issue.
3- Always read [help](https://github.com/persepolisdm/persepolis/wiki) first.
4- search your issue and make sure [it's not reported before](https://github.com/persepolisdm/persepolis/issues/477). Please ALWAYS IN ANY PROJECT read the issue template!  Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one.
5 - We use [GPL3 licence](https://github.com/persepolisdm/persepolis/blob/master/LICENSE). It means :  "This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY". Try to undestand it.
6- It is valuable to us that a user test the software and report us a problem. But we don't force users to do that or we don't pay them for it. so no need to report that how much time you spend for testing! Thanks!

**Comment by mavahedinia** [comment]
@okabbas Hi!
First of all I have to tell you when you are reporting issues, please provide full information and your logs; they help us inspect the issue!

1. There are a lot of apps which are closed by clicking on X, like iDMG. Therefore I guess it is neither a bug nor an issue, and is all about UX.

2. I have tested the app again and no unusual activity has been seen. Here I attached the related screenshots.
<img width="694" alt="screen shot 2018-04-03 at 15 51 28" src="https://user-images.githubusercontent.com/16556650/38246630-a7748496-3757-11e8-89f2-cfb4587c0b66.png">
<img width="666" alt="screen shot 2018-04-03 at 15 51 16" src="https://user-images.githubusercontent.com/16556650/38246631-a7b43d84-3757-11e8-8e6b-752323640fa1.png">

3. you can change or even develop (that is, Persepolis is free and open-source!) your own UI styles!

4. again I insist on providing logs while opening an issue! I tried to reproduce this but failed to do so and everything worked properly 🤔 You have to just simply get your logs from "Help>Show log file" and paste it on some pastebin like [beepaste.io](https://beepaste.io), then share the link here.

At last, please consider that Persepolis DM is a **free** app licensed under GPLv3 so everyone including you can participate and solve its problems or even develop their own features!

**Comment by alireza-amirsamimi** [comment]
Default style in mac is wrong.

**Comment by alireza-amirsamimi** [comment]
I fixed default style problem in mac.
