### ISSUE TITLE
Can't Upgrade using PPA

### ISSUE THREAD

**Issue by hoseinit** [persepolisdm/persepolis#493]
**System Details:**
* Operating System: Linux 
* Distro(For GNU/Linux and BSD users): Mint 18.3
* Desktop Environment(For GNU/Linux and BSD users): Cinnamon
* Persepolis Version: 3.0.1.0
* How do you install Persepolis? (Repositories, source, ...) REPO

I can't Upgrade to version 3.1.0 due to the fact that it's not released for XENIAL in lunchpad but it's okay for ARTFUL

**Comment by hayyan71** [comment]
@hoseinit Some packages in ubuntu 16.04 repos are too old. Persepolis 3.1.0 need newer version of youtube-dl, but it's not available in official repos for ubuntu 16.04. So, the latest .deb package for Xenial is 3.0.1.

You may install persepolis from source: https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction-fa

Regards

**Comment by salahoued** [comment]
@hayyan71 I see, OK that's why I can't upgrade PDM to the latest version, but still I did install ``youtube-dl`` with ``pip`` so I have the latest of ``youtube-dl``, so why it's can't be detected or used by PDM.

An other question is why PDM isn't delivered as a python package so that it can be installed with ``pip``

**Comment by alireza-amirsamimi** [comment]
@salahoued Hello
1- Some youtube-dl packages in unofficial repositories don't have standard packages so Persepolis can't import youtube-dl as a Python module and you'll get error.
2- Persepolis can be in pypi repository.
