### ISSUE TITLE
Connecting to aria2 daemon with rpc token

### ISSUE THREAD

**Issue by gbcox** [persepolisdm/persepolis#551]
I have an aria2 daemon running on my system using a RPC token and want to use this for
persepolis.  I don't see any options in the preferences or configuration to do this...  am I missing something or is this something that has not yet been included.  Thank you.

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting. I'll work on it :)

**Comment by ilwsm** [comment]
Still not implement?
This is a shame.

**Comment by JafarAkhondali** [comment]
I'll close this since you opened a new issue.
Our team was not active for a while and we are not getting paid to develop PDM so please don't consider development of the PDM as our obligation. We are just developing with love, if you love open source and need this feature, help us by creating a PR :relaxed:

**Comment by ilwsm** [comment]
Open Source is not an excuse!

**Comment by JafarAkhondali** [comment]
@goodandrewsoft Did i say it is?

>  The four essential freedoms
> 
> A program is free software if the program's users have the four essential freedoms: [1]
> 
>     The freedom to run the program as you wish, for any purpose (freedom 0).
>     The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
>     The freedom to redistribute copies so you can help others (freedom 2).
>     The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

We are developing under these rules! You are free to read, edit and redistribute our code but you cannot order or insult team members for doing it freely. If there was a premium version o PDM with support you could, but since it's completely free, you have no right to command us, meanwhile we try our best to improve the DM.

Please think about your words and our duty twice.

**Comment by ilwsm** [comment]
1. Why are you showing me these laws, I'm still not going to declare to the police or something like that.  
2. You are not obliged to me or to anyone else.  You are obliged only to your conscience or common sense in this situation.  You are right, I have no right to demand something, but nevertheless I would not be sitting calmly without implementing this feature.

**Comment by JafarAkhondali** [comment]
1. Because you said "Open Source is not an excuse!"
2. We've added this feature to our todo list, but there are tons of other features that are waiting to be implemented, we'll complete them ASAP.

**Comment by ilwsm** [comment]
> but there are tons

RPC feature must be one of the main, IMHO. 
And it is very strange to me why you haven’t implemented yet it in the server-side program, like this.

**Comment by JafarAkhondali** [comment]
Consider that as our fault, but choosing which features to implement first is what made the DMs different.
We'll try to work on it

**Comment by ilwsm** [comment]
🍺🍺🍺

**Comment by gbcox** [comment]
Duplicate of #244
