### ISSUE TITLE
persepolis not available for mageia or pclinuxos

### ISSUE THREAD

**Issue by fadi123go** [persepolisdm/persepolis#893]
please persepolis team can you create an rpm package for  mageia or pclinuxos, or at least an appimage. Thanks.

**Comment by RafaelLinux** [comment]
Same for openSUSE. Referenced link for openSUSE is empty. Simplest way to make it work any Linux is thru an AppImage.

**Comment by alireza-amirsamimi** [comment]
Unfortunately, our team member who made the package for openSUSE is not available now.  We have small team and each of us is a user of a specific operating system. for example I'm ArchLinux user. The process of making the package is unique for each distribution and maintainer of package must be familiar with that specific distribution. Obviously, our small team cannot be users of all Linux distributions. So we welcome those who volunteer to make and maintain  the package.

**Comment by RafaelLinux** [comment]
That's why I suggest to create an AppImage for Linux users. I have more than 25 applications running in any Linux cause they are AppImage version and avoid any Linux OS version dependence.

**Comment by alireza-amirsamimi** [comment]
We are working on the Persepolis standalone version for the new version.  But We did not succeed yet for GNU/Linux operating systems. We keep trying...

**Comment by RafaelLinux** [comment]
Thank you for continue trying. There is a lot of application developers packaking in AppImage, maybe they can help you on that

**Comment by Azathothas** [comment]
It's also possible to use [Nix-AppImage](https://github.com/ralismark/nix-appimage) to create an AppImage, I have done it here:
- https://github.com/Azathothas/Toolpacks-Extras/blob/main/.github/scripts/x86_64-Linux/pkgs/persepolis.sh
- https://github.com/Azathothas/Toolpacks-Extras/blob/main/.github/scripts/aarch64-Linux/pkgs/persepolis.sh

To test a premade build:
- https://pub.ajam.dev/temp/persepolis.NixAppImage

However, due to issues like: https://github.com/ralismark/nix-appimage/issues/10
Some features may not work. And the verison in nixpkgs is also old.
So best, if the official maintainers themselves release this.

![image](https://github.com/user-attachments/assets/074a89f6-6816-4699-b0cb-bdbbb547d946)

**Comment by RafaelLinux** [comment]
That AppImage works!!! Thx

**Comment by alireza-amirsamimi** [comment]
@RafaelLinux 
Please, checkout this [link](https://github.com/persepolisdm/persepolis/wiki/open-suse-Installer) for installing the latest Persepolis version on openSUSE.
