### ISSUE TITLE
Failed to fetch media on windows 

### ISSUE THREAD

**Issue by kuchingneko28** [persepolisdm/persepolis#905]
**System Details:**
* Operating System: Windows 10
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 3.2.0
* How do you install Persepolis? (Repositories, source, ...) : https://github.com/persepolisdm/persepolis/releases/tag/3.2.0

* _Please attach log files if crash or paste error message_

Error when fetch media : 
![{2288D71E-5008-4943-8E71-15739238EEBC} png](https://user-images.githubusercontent.com/73223302/156451865-377fa844-eabb-4444-9c80-c08733c95354.jpg)

 YouTube said: Unable to extract video data

Any help ?

**Comment by mclose90-cmd** [comment]
This is likely due to YouTube DRM protections. The video is DRM encoded to protect copyrights. Try using yt-dlp instead: https://github.com/yt-dlp/yt-dlp 

If you use yt-dlp, make sure you get the ffmpeg .exes as well. Place the ffmpeg .exes in the same folder as the yt-dlp.exe file. yt-dlp should be able to decode and download YouTube videos. 

Regards.
