### ISSUE TITLE
Allow building Persepolis from source on macOS

### ISSUE THREAD

**Issue by iFreilicht** [persepolisdm/persepolis#943]
**System Details:**
* Operating System: macOS
* Persepolis Version: 4.0.0
* How do you install Persepolis? source

**Issue Description and steps to reproduce:**
Right now, it is pretty difficult to build Persepolis from source on macOS. In nixpkgs, we maintain multiple patches (see https://github.com/NixOS/nixpkgs/tree/6d38aff4fc4f8b7606262ddb45e361e1c2863892/pkgs/tools/networking/persepolis) to make it possible.

I would like to upstream these patches to this repository, so that everyone is able to build Persepolis from source on macOS.

@alireza-amirsamimi Would you accept a PR that enables this? I'll gladly write it! I know that you build Persepolis for macOS with https://github.com/persepolisdm/mac-package-build, but for third party repositories like nixpkgs, HomeBrew or MacPorts, having a canonical way to build from source is very helpful.

**Comment by Maders** [comment]
Hey @iFreilicht,

Thanks for diving into this. Your work on the nixpkgs is pretty cool, and it's clear you've put a lot of effort into it.

We're all for having a unified process to build Persepolis from the source across all major systems.
Also, we're planning to transition to the `Meson` build system soon since `setup.py` is on its way out.

Regarding the [mac-package-build](https://github.com/persepolisdm/mac-package-build) repo, you're right; it's somewhat outdated. Currently, it serves more as a set of instructions for us, but we're eager to update and improve it. (any ideas or contributions are more than welcome!)

**Comment by iFreilicht** [comment]
Ok, that sounds awesome! Please ping me once you have a branch with `Meson` ready to test, I'll gladly try it out and offer feedback!
