### ISSUE TITLE
[macOS] 4.0.1: ARM / Apple Silicon download is actually an Intel version

### ISSUE THREAD

**Issue by core-code** [persepolisdm/persepolis#948]
i've downloaded ```Persepolis.Download.Manager.M.Chips.dmg``` and expected it to be native for "M-Chips".

however, it seems to be an intel binary:

<img width="276" alt="Screenshot 2024-03-14 at 18 18 38" src="https://github.com/persepolisdm/persepolis/assets/1261954/fc60053b-26b2-4701-baa8-9782d279b5d7">

**Comment by kiahamedi** [comment]
Hello @core-code 

Thank you for letting us know

In our opinion, this case is also strange because the package that is output for Arm(M Chips), only runs on M Chips, and Intel versions can be run on Intel and M Chips in our tests.

We believe that the issue is due to packaging in the PyInstaller structure, and we will try to solve this issue for the next version.

Best wishes
