### ISSUE TITLE
Updating via brew fails with a 404

### ISSUE THREAD

**Issue by rdash99** [persepolisdm/persepolis#971]
**System Details:**
* Operating System: MacOS 14.3.1
* Persepolis Version: 14.3.1
* How do you install Persepolis? (Repositories, source, ...) HomeBrew

``` Upgrading persepolis-download-manager
==> Downloading https://github.com/persepolisdm/persepolis/releases/download/4.0.1/Persepolis.Download.Manager.M.Chips.dmg
curl: (22) The requested URL returned error: 404                                                                                                                                                           

==> Purging files for version 4.0.1 of Cask persepolis-download-manager
Error: persepolis-download-manager: Download failed on Cask 'persepolis-download-manager' with message: Download failed: https://github.com/persepolisdm/persepolis/releases/download/4.0.1/Persepolis.Download.Manager.M.Chips.dmg
```

**Issue Description and steps to reproduce:**

Attempt to update Persepolis on an M1 MacBook Air - I also tried to get Brew to reinstall it but that also failed in the same way

**Comment by kiahamedi** [comment]
Hello dear @rdash99 

Yes we are currently having problems with the Brew system and our request for a new version from the Brew failed due to their closed package structure.
We will fix this issue in the next tag version and install via Brew will be available again.
You can use [direct download](https://github.com/persepolisdm/persepolis/releases/tag/4.0.1) and replace with the old version.
